### ISSUE TITLE
Errors occur in mlnx-ofed-4.9-driver/build.sh when install KRCORE modified version of Mellanox OFED driver

### ISSUE THREAD

**Issue by LiuMicheal** [SJTU-IPADS/krcore-artifacts#5]
Dear authors, there is a step in krcore-artifacts/docs/install.md when install your modified version of Mellanox OFED driver:
cd ${PROJECT_PATH}/mlnx-ofed-4.9-driver
sh build.sh

When I run build.sh, there occurs:
tar (child): mlnx-ofed-kernel_4.9.orig.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tail: cannot open 'mlnx-ofed-kernel-4.9/debian/changelog' for reading: No such file or directory
dpkg-source: error: tail of mlnx-ofed-kernel-4.9/debian/changelog subprocess returned exit status 1
tail: cannot open 'debian/changelog' for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog subprocess returned exit status 1
mv: cannot stat 'mlnx-ofed-kernel-dkms_4.9-OFED.4.9.3.1.5.1_all.deb': No such file or directory
dpkg: error: cannot access archive 'mlnx-ofed-kernel-dkms_4.9-OFED.4.9.3.1.5.1_all_new.deb': No such file or directory

In build.sh, there exists one command:
tar zxf mlnx-ofed-kernel_4.9.orig.tar.gz

May I ask what the **mlnx-ofed-kernel_4.9.orig.tar.gz** is?  Does it mean MLNX_OFED_LINUX-4.9-3.1.5.0-ubuntu18.04-x86_64.tgz?
I would be very appreciate it.

**Comment by wxdwfc** [comment]
The `mlx-ofed-kernel_4.9.orig.tar.gz` can be downloaded from https://developer.nvidia.com/networking/mlnx-ofed-eula?mtag=linux_sw_drivers&mrequest=downloads&mtype=ofed&mver=MLNX_OFED-5.8-4.1.5.0&mname=MLNX_OFED_LINUX-5.8-4.1.5.0-ubuntu20.04-x86_64.tgz, thanks.

**Comment by LiuMicheal** [comment]
Got it, I will try. Thanks a lot.

**Comment by LiuMicheal** [comment]
I want to give a more specific position of **mlx-ofed-kernel_4.9.orig.tar.gz**. Take MLNX_OFED_LINUX-4.9-3.1.5.0-ubuntu18.04-x86_64 as an example.
MLNX_OFED_LINUX-4.9-3.1.5.0-ubuntu18.04-x86_64/src/MLNX_OFED_SRC-4.9-3.1.5.0/SOURCES/mlnx-ofed-kernel_4.9.orig.tar.gz
Then build.sh runs correctly. Thanks.
